log_dir: "/home/intermine/git_ratmine/ratmine_src_data/download_logs"
data_dir: "/home/intermine/git_ratmine/ratmine_src_data/tmp/"

default_sources:
  - "UniProt"

UniProt:
    organisms:
        - 10116
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 943925
        - 943926

